# Generated by Django 4.0.4 on 2022-07-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_delete_followerscount_delete_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='title',
        ),
    ]
